import './globals.css'
import type { Metadata } from 'next'
import localFont from 'next/font/local'

const danaFont = localFont({
  src: './DanaVF.woff2',
  display: 'swap',
  variable: '--font-dana',
})

export const metadata: Metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
}

export default function RootLayout({
  children,
}: {
  children: React.ReactNode
}) {
  return (
    <html lang="fa" className={danaFont.variable}>
      <body dir="rtl">{children}</body>
    </html>
  )
}
